server:
  port: 8090

logging:
  level:
    org:
      springframework:
        security: debug

# APIエンドポイント設定
endpoint:
  uri: http://localhost:8080/

path:
  CERT_PROCCESSING_PATH: /authenticate
  LOGIN_PATH: /login
  DEFAULT_SUCCESS_PATH: /timeline
  LOGOUT_PATH: /logout
  REGIST_PATH: /registration

role:
  USER: USER
  ADMIN: ADMIN

date:
  year:
    max: 2019
  month:
    min: 1
    max: 12
  day:
    min: 1
    max: 31

