server:
  port: 8090

logging:
  level:
    org:
      springframework:
        security: debug

# APIエンドポイント設定
endpoint:
  uri: http://localhost:8080/

path:
  CERT_PROCCESSING_PATH: /authenticate
  LOGIN_PATH: /login
  DEFAULT_SUCCESS_PATH: /timeline
  LOGOUT_PATH: /logout
  REGIST_PATH: /registration

role:
  USER: USER
  ADMIN: ADMIN

date:
  year:
    max: 2019
  month:
    min: 1
    max: 12
  day:
    min: 1
    max: 31

# mail 設定
mail:
  user: adelypenguin3193@gmail.com
  host: smtp.gmail.com
  from: adelypenguin3193@gmail.com
  password: jedi@334force
  charset: UTF-8
  encoding: base64
  port: 587
  starttls: true
  connectiontimeout: 10000
  timeout: 10000
  debug: true
  auth: true